version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
      day: saturday
      timezone: America/New_York
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: monthly
