version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    day: saturday
    timezone: America/New_York
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: tslint
    versions:
    - "> 5.20.1"
