baseurl: https://www.amoscato.com
languageCode: en-us
title: Nick Amoscato
params:
  title: Nick Amoscato
  summary: Software Engineer, Designer, Musician from Pittsburgh
  description: Nick is a software engineer, designer, and musician with a passion for maintainable architecture, usable experiences, and jazz.
  images:
    - /img/feature-image.jpg
googleAnalytics: G-JRTT983WST
taxonomies:
  category: categories
markup:
  highlight:
    style: monokai
  goldmark:
    renderer:
      unsafe: true
