name: Deploy

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      NODE_VERSION: 10.x

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ NODE_VERSION }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ NODE_VERSION }}
    - name: Deploy
      env:
        SUPPRESS_NO_CONFIG_WARNING: 1
        FTP_HOST: ${{ secrets.FTP_HOST }}
        FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
        FTP_USER: ${{ secrets.FTP_USER }}
      run: |
        npm install
        npm run deploy
